eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/api/student/**
  sleuth:
   reactor:
      instrumentation-type: decorate-on-each
  zipkin:
    base-url: http://localhost:9411